# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    classification_report, confusion_matrix,
    mean_absolute_error, mean_squared_error
)
import warnings
warnings.filterwarnings('ignore')

print('✅ All libraries imported successfully')

np.random.seed(42)

def generate_indian_numbers(n):
    numbers = []
    prefixes = ['6', '7', '8', '9']
    for _ in range(n):
        prefix = np.random.choice(prefixes)
        rest   = ''.join([str(np.random.randint(0, 10)) for _ in range(9)])
        numbers.append(prefix + rest)
    return numbers

def calculate_risk_score(total_calls, unique_numbers, avg_duration_min,
                          calls_per_hour, spam_reports):
    score = 0.0

    if calls_per_hour <= 3:
        score += 0.0
    elif calls_per_hour <= 6:
        score += 1.0
    elif calls_per_hour <= 10:
        score += 1.8
    else:
        score += 2.5

    spam_ratio = spam_reports / (total_calls + 1)
    score += min(spam_ratio * 10, 3.0)

    if avg_duration_min < 0.5:
        score += 2.0
    elif avg_duration_min < 1.5:
        score += 1.2
    elif avg_duration_min < 3.0:
        score += 0.5
    else:
        score += 0.0

    diversity = unique_numbers / (total_calls + 1)
    score += min(diversity * 2.5, 1.5)

    if total_calls > 100:
        score += 1.0
    elif total_calls > 50:
        score += 0.5
    elif total_calls > 20:
        score += 0.2

    return round(min(score, 10.0), 2)


n_scam = 200
total_calls_scam    = np.random.randint(50, 150, n_scam)
unique_scam         = np.array([np.random.randint(int(t*0.5), t+1)
                                for t in total_calls_scam])
spam_scam           = np.array([np.random.randint(int(t*0.1), t+1)
                                for t in total_calls_scam])
duration_scam       = np.round(np.random.uniform(0.1, 1.4, n_scam), 2)
cph_scam            = np.round(np.random.uniform(7.0, 30.0, n_scam), 2)

scam_records = {
    'call_no'                 : generate_indian_numbers(n_scam),
    'total_calls_made'        : total_calls_scam,
    'unique_numbers_contacted': unique_scam,
    'avg_call_duration_min'   : duration_scam,
    'calls_per_hour'          : cph_scam,
    'spam_reports'            : spam_scam,
    'is_scam'                 : [1] * n_scam,
}

n_safe = 300
total_calls_safe    = np.random.randint(1, 25, n_safe)
unique_safe         = np.array([np.random.randint(1, min(t+1, 15)+1)
                                for t in total_calls_safe])
spam_safe           = np.array([np.random.randint(0, min(t+1, 3))
                                for t in total_calls_safe])
duration_safe       = np.round(np.random.uniform(2.0, 15.0, n_safe), 2)
cph_safe            = np.round(np.random.uniform(0.1, 2.5, n_safe), 2)

safe_records = {
    'call_no'                 : generate_indian_numbers(n_safe),
    'total_calls_made'        : total_calls_safe,
    'unique_numbers_contacted': unique_safe,
    'avg_call_duration_min'   : duration_safe,
    'calls_per_hour'          : cph_safe,
    'spam_reports'            : spam_safe,
    'is_scam'                 : [0] * n_safe,
}

df = pd.concat([pd.DataFrame(scam_records), pd.DataFrame(safe_records)],
               ignore_index=True)

df['risk_score'] = df.apply(
    lambda row: calculate_risk_score(
        row['total_calls_made'],
        row['unique_numbers_contacted'],
        row['avg_call_duration_min'],
        row['calls_per_hour'],
        row['spam_reports']
    ), axis=1
)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df_clean = df.copy()
df_clean = df_clean.drop(columns=['call_no'])

for col in df_clean.select_dtypes(include=np.number).columns:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

df_clean = df_clean.drop_duplicates()

for col in ['calls_per_hour', 'avg_call_duration_min']:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    df_clean[col] = df_clean[col].clip(Q1 - 1.5*IQR, Q3 + 1.5*IQR)

df_feat = df_clean.copy()

df_feat['call_diversity_ratio'] = (
    df_feat['unique_numbers_contacted'] / (df_feat['total_calls_made'] + 1)
).round(4)

df_feat['short_call_flag'] = (df_feat['avg_call_duration_min'] < 1.0).astype(int)
df_feat['high_freq_flag'] = (df_feat['calls_per_hour'] > 6).astype(int)

df_feat['spam_intensity'] = (
    df_feat['spam_reports'] / (df_feat['total_calls_made'] + 1)
).round(4)

df_feat['suspicion_score'] = (
    0.30 * df_feat['calls_per_hour'] +
    0.30 * df_feat['spam_reports'] +
    0.20 * df_feat['short_call_flag'] * 10 +
    0.20 * df_feat['call_diversity_ratio'] * 10
).round(4)

FEATURE_COLS = [
    'total_calls_made', 'unique_numbers_contacted', 'avg_call_duration_min',
    'calls_per_hour', 'spam_reports',
    'call_diversity_ratio', 'short_call_flag', 'high_freq_flag',
    'spam_intensity', 'suspicion_score'
]

X        = df_feat[FEATURE_COLS]
y_class  = df_feat['is_scam']
y_risk   = df_feat['risk_score']

X_train, X_test, yc_train, yc_test, yr_train, yr_test = train_test_split(
    X, y_class, y_risk, test_size=0.2, random_state=42, stratify=y_class
)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)

rf_clf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_clf.fit(X_train_s, yc_train)

rf_reg = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rf_reg.fit(X_train_s, yr_train)

def call_signal_analysis(call_data: dict) -> dict:
    tc   = call_data['total_calls_made']
    uc   = call_data['unique_numbers_contacted']
    dur  = call_data['avg_call_duration_min']
    cph  = call_data['calls_per_hour']
    spam = call_data['spam_reports']

    call_diversity_ratio = uc / (tc + 1)
    short_call_flag      = int(dur < 1.0)
    high_freq_flag       = int(cph > 6.0)
    spam_intensity       = spam / (tc + 1)
    suspicion_score      = (
        0.30 * cph +
        0.30 * spam +
        0.20 * short_call_flag * 10 +
        0.20 * call_diversity_ratio * 10
    )

    feature_vector = [[
        tc, uc, dur, cph, spam,
        call_diversity_ratio, short_call_flag, high_freq_flag,
        spam_intensity, suspicion_score
    ]]

    scaled = scaler.transform(feature_vector)

    is_scam_pred = int(rf_clf.predict(scaled)[0])
    scam_prob    = round(float(rf_clf.predict_proba(scaled)[0][1]) * 100, 2)
    ml_risk      = round(float(np.clip(rf_reg.predict(scaled)[0], 0, 10)), 2)

    rule_risk = calculate_risk_score(tc, uc, dur, cph, spam)

    final_risk = round(0.65 * ml_risk + 0.35 * rule_risk, 2)
    final_risk = round(min(final_risk, 10.0), 2)

    if final_risk >= 7.5:
        risk_level = 'HIGH'
    elif final_risk >= 5.0:
        risk_level = 'MEDIUM-HIGH'
    elif final_risk >= 3.0:
        risk_level = 'MEDIUM'
    elif final_risk >= 1.5:
        risk_level = 'LOW-MEDIUM'
    else:
        risk_level = 'LOW'

    return {
        'source'       : 'call',
        'call_no'      : call_data.get('call_no', 'Unknown'),
        'risk_score'   : final_risk,
        'risk_level'   : risk_level,
        'is_scam_pred' : is_scam_pred,
        'scam_prob'    : scam_prob,
        'flags'        : []
    }